### ISSUE TITLE
Markdown broken on CMakePresets.json page & confusing explanation

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg-docs#257]
Hi,

On this page here, the Markdown looks broken:

![image](https://github.com/microsoft/vcpkg-docs/assets/4967343/945b48ae-77d6-410f-bfff-22e3de5dfa13)

If I interpret the broken Markdown correctly, you'd have **two** entries in `CMakePresets.json`, one `default` and one named `vcpkg` - and both would set `"CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"`? That somehow doesn't make sense to me. And then you have a `CMakeUserPresets.json` that sets the environment variable `VCPKG_ROOT`, but inherits the `vcpkg` preset from `CMakePresets.json` (which in turn depends on the environment variable)? It all doesn't really make sense to me, and I think that section would benefit from a better explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b
* Version Independent ID: 6402b87a-b33e-ebf5-01d2-a2d1115d6f2b
* Content: [Install and use packages with CMake in Visual Studio Code](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode)
* Content Source: [vcpkg/get_started/get-started-vscode.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/get_started/get-started-vscode.md)
* Service: **vcpkg**
* GitHub Login: @data-queue
* Microsoft Alias: **danshaw2**

**Comment by vicroms** [comment]
I fixed the broken markdown on #266

**Comment by patrikhuber** [comment]
@vicroms It's still broken on the live website https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vscode?pivots=shell-cmd. Does it take some more time to deploy?

Also have you given my comment / question for clarification any thought?

> If I interpret the broken Markdown correctly, you'd have **two** entries in `CMakePresets.json`, one `default` and one named `vcpkg` - and both would set `"CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"`? That somehow doesn't make sense to me. And then you have a `CMakeUserPresets.json` that sets the environment variable `VCPKG_ROOT`, but inherits the `vcpkg` preset from `CMakePresets.json` (which in turn depends on the environment variable)? > It all doesn't really make sense to me, and I think that section would benefit from a better explanation.
