### ISSUE TITLE
$schema URL is a 404

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg-docs#53]
Hi,

The `$schema` URL given in https://learn.microsoft.com/en-us/vcpkg/users/manifests is a 404: https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json.

```
"$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 249966f4-5235-b31a-cdfd-007401b3315c
* Version Independent ID: 249966f4-5235-b31a-cdfd-007401b3315c
* Content: [Manifest mode](https://learn.microsoft.com/en-us/vcpkg/users/manifests)
* Content Source: [vcpkg/users/manifests.md](https://github.com/Microsoft/vcpkg-docs/blob/main/vcpkg/users/manifests.md)
* Product: **vcpkg**
* GitHub Login: @ras0219-msft
* Microsoft Alias: **roschuma**

**Comment by ras0219-msft** [comment]
Fixed by https://github.com/microsoft/vcpkg-docs/pull/55. Thanks for the report!

**Comment by patrikhuber** [comment]
@ras0219-msft I'm still getting a 404 on the updated URL, and looking through https://github.com/microsoft/vcpkg/tree/master/scripts, I can't find any schema there. Apologies if I'm just really blind.

**Comment by patrikhuber** [comment]
Is it perhaps this file / URL?
https://github.com/microsoft/vcpkg-tool/blob/main/docs/vcpkg.schema.json
